export const HighlightMap: Record<string, string> = {
  'React.js': 'reactjs',
  'Next.js': 'nextjs',
  'React Native': 'reactnative',
  AXA: 'axa',
  'AXA HUMA': 'axa-huma',
  AppBar: 'appbar',
  'AXA PerksBar CMS': 'axa-perksBar-cms',
  'AIA CMS': 'aia-cms',
  AIA: 'aia',
  'Brick Extreme LLC': 'brick-extreme-llc',
  'World of Minifigs Builder': 'world-of-minifigs-builder',
  LEGO: 'lego',
  NestJS: 'nest-js',
};
